### ISSUE TITLE
Old GNU ld bfd broken on meson 0.63.2, works on 0.60.1

### ISSUE THREAD

**Issue by laffer1** [mesonbuild/meson#10823]
**Describe the bug**
Unable to build projects using system ld 

ld.bfd 2.17.50

**To Reproduce**
Tested with gobject-introspection 1.72.0, webrtc-audio-processing 1.0

Attempt build with system compiler (clang 10.0.1 + ld.bfd) 

**Expected behavior**
Code compiles and links

**system parameters**
* native build
* Fails on FreeBSD 11.4 and MidnightBSD 2.2
* Python 3.8.13
* meson 0.63.2
* ninja 1.11.1

Code builds with LLVM 9 or 10 from ports, which is finding the LLVM linker.  Some code works with GCC10 from ports also as it's not using the system linker.   System compiler works with meson 0.60.1.

**Comment by eli-schwartz** [comment]
This is missing the bug report part of this bug report -- can you post the error log?

**Comment by laffer1** [comment]
[meson-log.txt](https://github.com/mesonbuild/meson/files/9591922/meson-log.txt)
[typescript.txt](https://github.com/mesonbuild/meson/files/9591924/typescript.txt)

Here is the meson-log.txt and output from script during a build in the ports tree of webrtc-audio-processing on the MidnightBSD 2.2 amd64 system.

**Comment by laffer1** [comment]
FreeBSD 11.4 i386 meson log
[freebsd-meson-log.txt](https://github.com/mesonbuild/meson/files/9591939/freebsd-meson-log.txt)

**Comment by laffer1** [comment]
Meson 0.60.1 logs from the MidnightBSD 2.2 amd64 system showing a working build. 

[60.1-meson-log.txt](https://github.com/mesonbuild/meson/files/9591950/60.1-meson-log.txt)
[60.1-typescript.txt](https://github.com/mesonbuild/meson/files/9591951/60.1-typescript.txt)

**Comment by laffer1** [comment]
I've been able to determine that 0.62.0 is also broken.

**Comment by laffer1** [comment]
It was commit 0a3a9fa0c3ebf45c94d9009a59cead571cbecf7b

**Comment by laffer1** [comment]
I think a better fix rather than a bunch of OS checks here is if it's an older GNU ld, disable the "thin" optimization.  This would fix macOS, illuminos, FreeBSD, and others using an older GNU ld.

**Comment by giordano** [comment]
I'm also having the same issue.  Also, #8057 asked for a way to _optionally_ enable thin archiving, instead #9294 forcibly enables it without a way to disable it, which creates the exact opposite problem when a dynamic linker can't deal with thin archives.

**Comment by giordano** [comment]
> I'm also having the same issue. 

More specifically, I have the same issue with thin archives being rejected by the dynamic linker when cross-compiling for macOS, but these lines
https://github.com/mesonbuild/meson/blob/c8d5f93cb0b7ebc30aec637a9aeadbe5bc9934d6/mesonbuild/linkers/linkers.py#L210-L215
look like `T` shouldn't even be used when targeting macOS, except it doesn't clearly seem to happen in my case.  For reference, my cross file is
```toml
[binaries]
c = '/opt/bin/x86_64-apple-darwin14-libgfortran3-cxx03/x86_64-apple-darwin14-clang'
cpp = '/opt/bin/x86_64-apple-darwin14-libgfortran3-cxx03/x86_64-apple-darwin14-clang++'
fortran = '/opt/bin/x86_64-apple-darwin14-libgfortran3-cxx03/x86_64-apple-darwin14-gfortran'
objc = '/opt/bin/x86_64-apple-darwin14-libgfortran3-cxx03/x86_64-apple-darwin14-cc'
ar = '/opt/bin/x86_64-apple-darwin14-libgfortran3-cxx03/x86_64-apple-darwin14-ar'
ld = '/opt/bin/x86_64-apple-darwin14-libgfortran3-cxx03/x86_64-apple-darwin14-ld'
nm = '/opt/bin/x86_64-apple-darwin14-libgfortran3-cxx03/x86_64-apple-darwin14-nm'
strip = '/opt/bin/x86_64-apple-darwin14-libgfortran3-cxx03/x86_64-apple-darwin14-strip'
pkgconfig = '/usr/bin/pkg-config'

[built-in options]
c_args = ['-I/workspace/destdir/include']
cpp_args = ['-I/workspace/destdir/include']
fortran_args = ['-I/workspace/destdir/include']
objc_args = ['-I/workspace/destdir/include', '-x', 'objective-c']
c_link_args = ['-L/workspace/destdir/lib']
cpp_link_args = ['-L/workspace/destdir/lib']
fortran_link_args = ['-L/workspace/destdir/lib']
objc_link_args = ['-L/workspace/destdir/lib']
prefix = '/workspace/destdir'

[properties]
needs_exe_wrapper = true
cmake_toolchain_file = '/opt/toolchains/x86_64-apple-darwin14-libgfortran3-cxx03/target_x86_64-apple-darwin14.cmake'
cmake_defaults = false

[build_machine]
system = 'linux'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'

[host_machine]
system = 'darwin'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'
```
