### ISSUE TITLE
[feature] pre-commit hooks

### ISSUE THREAD

**Issue by Freed-Wu** [mesonbuild/meson#13114]
Is it possible to add a [pre-commit](https://pre-commit.com/) hook for `meson format`?

TIA!

**Comment by tristan957** [comment]
how do we do that

**Comment by dcbaker** [comment]
Possibly relevant: https://github.com/mesonbuild/meson/pull/13099

**Comment by eli-schwartz** [comment]
https://git-scm.com/docs/githooks

It's pretty simple to add, because hooks are just a shell script that gets run at the time of committing. So you can just write a script that does that (and other things).

**Comment by tristan957** [comment]
I don't think there is any benefit to being pedantic, Eli. It is fairly obvious what this user wants. I don't understand why we cannot just have a rational discussion about alternatives to committing this to the repo.

**Comment by trim21** [comment]
I setup a pre-commit mirror for meson https://github.com/trim21/pre-commit-mirror-meson

another option if you do not want a third part mirror you don't trust:

```yaml
  - repo: local
    hooks:
      - id: meson
        name: meson
        language: python
        entry: meson format -e -i
        files: ^(.*/)?(meson\.build|meson\.options)$
        additional_dependencies: ['meson==1.6.1']
```
