### ISSUE TITLE
Publish Meson as a Docker container

### ISSUE THREAD

**Issue by xordspar0** [mesonbuild/meson#3887]
The documentation mentions how to get Meson inside [Docker running in Travis](http://mesonbuild.com/Continuous-Integration.html#travis-for-os-x-and-linux-with-docker), but it would be great if Meson was available as a Docker container for other CI/CD platforms that use Docker natively, like [Drone](https://drone.io/), GitLab CI, and CircleCI. Then, instead of installing Meson and Ninja on every build, I could just do:

```yaml
pipeline:
  build:
    when:
      event: push
    image: mesonbuild/meson
    commands:
      - meson builddir
      - ninja -C builddir
      - ninja -C builddir test
```
