### ISSUE TITLE
[RFC] Use CircleCI for linux CI

### ISSUE THREAD

**Issue by lazka** [mesonbuild/meson#3915]
https://circleci.com/gh/lazka/workflows/meson

https://circleci.com/gh/lazka/meson/68#config/containers/0

Running all linux jobs takes 12 minutes there.

Theoretically this should shave off 10 minutes of the macos+linux tests if macOS stays on travis-ci.

The reason for this is that I saw that meson is using docker, thus easy to port, and I had good experience with circleci's speed on other projects so far.

Feel free to close this :)

**Comment by nirbheek** [comment]
How many concurrent jobs does Circle CI provide? Travis gives us 5 at once.

If it is indeed much faster, we can move. However, the major bottleneck in our CI is appveyor right now.

**Comment by lazka** [comment]
> How many concurrent jobs does Circle CI provide? Travis gives us 5 at once.

4

> If it is indeed much faster, we can move. However, the major bottleneck in our CI is appveyor right now.

yeah, depends on what you need/want. and no idea re appveyor :(

Here is the config, in case the above logs disappear for some reason:
<details>

```yaml

defaults: &defaults
  working_directory: ~/project
  docker:
    - image: jpakkane/mesonci:bionic
  steps:
    - checkout
    - run: python ./skip_ci.py --base-branch-env=CIRCLE_BRANCH --is-pull-env=CIRCLE_PR_NUMBER
    - run: mkdir -p tools
    - run: wget -c http://nirbheek.in/files/binaries/ninja/linux-amd64/ninja -O ./tools/ninja
    - run: chmod +x ./tools/ninja
    - run: CC=$CC CXX=$CXX OBJC=$CC OBJCXX=$CXX PATH="$PWD"/tools:$PATH MESON_FIXED_NINJA=1 ./run_tests.py $RUN_TESTS_ARGS -- $MESON_ARGS;

version: 2
jobs:
  job.gcc:
    environment:
      - CC: "gcc"
      - CXX: "g++"
    <<: *defaults
  job.clang:
    environment:
      - CC: "clang"
      - CXX: "clang++"
    <<: *defaults
  job.gcc.unity:
    environment:
      - CC: "gcc"
      - CXX: "g++"
      - MESON_ARGS: "--unity=on"
    <<: *defaults
  job.clang.unity:
    environment:
      - CC: "clang"
      - CXX: "clang++"
      - MESON_ARGS: "--unity=on"
    <<: *defaults
  job.gcc.cross:
    environment:
      - CC: "gcc"
      - CXX: "g++"
      - RUN_TESTS_ARGS: "--cross"
    <<: *defaults
  job.gcc.cross.unity:
    environment:
      - CC: "gcc"
      - CXX: "g++"
      - RUN_TESTS_ARGS: "--cross"
      - MESON_ARGS: "--unity=on"
    <<: *defaults

workflows:
  version: 2
  build_and_test:
    jobs:
      - job.gcc
      - job.clang
      - job.gcc.unity
      - job.clang.unity
      - job.gcc.cross
      - job.gcc.cross.unity
```
</details>
