### ISSUE TITLE
Use meson with travis CI build

### ISSUE THREAD

**Issue by agauniyal** [mesonbuild/meson#465]
How do I configure my .travis.yaml to include meson build system, currently I'm doing it like this
```
sudo: required
language: cpp
compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise
    packages:
    - gcc-5
    - g++-5
    - clang-3.8

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install ninja python-pip python-dev build-essential
  - sudo pip install --upgrade pip
  - sudo pip install meson

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

script:
  - mkdir build
  - meson build
  - cd build
  - ninja
  - ninja test
```

but the build fails at `meson build` part with error message stating meson not found. But the step - `sudo pip install meson` successfully completes. And without sudo, it fails with permission denied.

How do I make `meson` available in `$PATH`?
