### ISSUE TITLE
Adding `ld` parameter in cross file causes crash

### ISSUE THREAD

**Issue by matanui159** [mesonbuild/meson#6449]
**Describe the bug**
All in the title

**To Reproduce**
```
project('mint2d', 'c', default_options: ['c_std=c99'])

executable(
   'mint2d', [
      'main.c'
   ]
)
```

```toml
[host_machine]
system = 'windows'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'

[binaries]
c = 'x86_64-w64-mingw32-gcc'
ar = 'x86_64-w64-mingw32-ar'
ld = 'x86_64-w64-mingw32-ld'
strip = 'x86_64-w64-mingw32-strip'
```

**Expected behavior**
To not crash and use that `ld`. Removing the `ld` parameter prevents the crash but its not immediate obvious

**Crashlog**
```
The Meson build system
Version: 0.53.999
Source dir: /home/matanui159/vscode/mint2d-meson
Build dir: /home/matanui159/vscode/mint2d-meson/bin
Build type: cross build
Project name: mint2d
Project version: undefined
C compiler for the build machine: cc (gcc 9.2.0 "cc (GCC) 9.2.0")
C linker for the build machine: cc GNU ld.bfd 2.33.1

meson.build:1:0: ERROR: Unable to determine dynamic linker

A full log can be found at /home/matanui159/vscode/mint2d-meson/bin/meson-logs/meson-log.txt
```

**system parameters**
* Cross build
* Manjaro 4.19.88
* Python 3.8.0
* Meson 0.53.999 from git
