### ISSUE TITLE
Generator incorrectly quotes command line arguments when parameters use a space (' ') instead of an equal (=)

### ISSUE THREAD

**Issue by SenorAgosto** [mesonbuild/meson#8086]
**Describe the bug**
Generator command line arguments have been quoted when parameters contain a space. 

I'm attempting to use a *generator* to generate some code, when I run `ninja` to build the project the generator step fails because the arguments have been quoted on the command line. I confirmed the generator runs correctly if I manually remove the quotes.

**To Reproduce**

The below meson.build demonstrates the issue. 

```
# meson.build
kaitai_c = find_program('ksc')

# NOTE: using a space instead of equals in --target param
gen_kaitai = generator(
    kaitai_c,
    output : ['@BASENAME@.h', '@BASENAME@.cpp'],
    arguments : [
        '--target cpp_stl',
        '--cpp-namespace @BASENAME@',
        '--cpp-standard 11',
        '--outdir @BUILD_DIR@',
        '@INPUT@',
    ]
)

# include all kaitai struct definition files here
kaitai_files = files('test.ksy')

gen_src = []
foreach gen_input : kaitai_files
    gen_src += gen_kaitai.process(gen_input)
endforeach

# create a dependency we can use from other meson directories
parse_lib = static_library('parse', gen_src, include_directories : [includes], dependencies : [kaitai])
parse = declare_dependency(sources : [gen_src], link_with : [parse_lib])
```

```
# test.ksy
meta:
  id: test
seq:
  - id: records
    type: buffer_with_len
    repeat: until
    repeat-until: _.len == 0
types:
  buffer_with_len:
    seq:
      - id: len
        type: u1
      - id: value
        size: len
enums:
  ip_protocol:
    1: icmp
    4: ip_tunnel
    6: tcp
    17: udp
```

Then `ninja` tries to run the following and it fails because ksc interprets '--target cpp_stl' as one argument instead of two. 
`ksc '--target cpp_stl' '--cpp-namespace test' '--cpp-standard 11' '--outdir feeds/libparse.a.p' ../feeds/test.ksy`

**Expected behavior**
I expect `ninja` to invoke the generator as:

`ksc --target cpp_stl --cpp-namespace test --cpp-standard 11 --outdir feeds/libparse.a.p ../feeds/test.ksy`

**Work around**
I noticed if I use equal (=) instead of spaces, the generated command does not quote the arguments and the generator step works correctly. 

```
gen_kaitai = generator(
    kaitai_c,
    output : ['@BASENAME@.h', '@BASENAME@.cpp'],
    arguments : [
        '--target=cpp_stl',
        '--cpp-namespace=@BASENAME@',
        '--cpp-standard=11',
        '--outdir=@BUILD_DIR@',
        '@INPUT@',
    ]
)
```

**system parameters**
- meson 0.56.0
- centos 7 under Windows Subsystem for Linux 2
- python 3.6.8
- ninja 1.9.0
